-- Flamingo schema 3: customers with a balance in their favor (saldo a favor).
-- The balance is a ledger (credit_movements) plus a cached, never-negative total.
-- Cash movements of the ledger inside a shift are part of the expected cash of its arqueo.
-- Ejecutar completo en Supabase → SQL Editor. Es atómico: si algo falla, no cambia nada.
-- Se niega a correr si el esquema no está en la versión 2 (fuera de orden o ya aplicada).
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '30s';
SELECT pg_advisory_xact_lock(704221, 1);
DO $guard$
BEGIN
  IF (SELECT value FROM flamingo.settings WHERE key='schema_version') IS DISTINCT FROM '2' THEN
    RAISE EXCEPTION 'Flamingo: esta migración (esquema 3) requiere el esquema 2. Revisa: SELECT value FROM flamingo.settings WHERE key=''schema_version'';';
  END IF;
END $guard$;
SET search_path TO flamingo, pg_catalog;
CREATE TABLE customers(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '',
  balance INTEGER NOT NULL DEFAULT 0 CHECK (balance >= 0),
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX customers_name_idx ON customers(lower(name));
CREATE TABLE credit_movements(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  amount INTEGER NOT NULL CHECK (amount <> 0),
  kind TEXT NOT NULL CHECK (kind IN ('deposit','change','sale','void','refund','adjust')),
  method TEXT NOT NULL CHECK (method IN ('cash','qr','card','none')),
  request_id TEXT UNIQUE,
  sale_id INTEGER REFERENCES sales(id),
  shift_id INTEGER REFERENCES shifts(id),
  user_id INTEGER NOT NULL REFERENCES users(id),
  note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX credit_movements_customer_idx ON credit_movements(customer_id, id DESC);
CREATE INDEX credit_movements_shift_idx ON credit_movements(shift_id);
CREATE INDEX credit_movements_sale_idx ON credit_movements(sale_id);
CREATE INDEX credit_movements_user_idx ON credit_movements(user_id);
CREATE INDEX customers_created_by_idx ON customers(created_by);
ALTER TABLE sales ADD COLUMN customer_id INTEGER REFERENCES customers(id);
ALTER TABLE sales ADD COLUMN credit INTEGER NOT NULL DEFAULT 0 CHECK (credit >= 0);
ALTER TABLE sales ADD COLUMN change_credit INTEGER NOT NULL DEFAULT 0 CHECK (change_credit >= 0);
CREATE INDEX sales_customer_idx ON sales(customer_id);
ALTER TABLE sales DROP CONSTRAINT balanced_payment;
ALTER TABLE sales ADD CONSTRAINT balanced_payment CHECK(total>0 AND cash>=0 AND qr>=0 AND card>=0 AND cash+qr+card+credit=total AND tendered>=cash AND change_due=tendered-cash AND change_credit<=change_due AND (credit=0 AND change_credit=0 OR customer_id IS NOT NULL));
GRANT SELECT,INSERT,UPDATE ON customers, credit_movements TO flamingo_app;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA flamingo TO flamingo_app;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY backend_access ON customers TO flamingo_app USING (true) WITH CHECK (true);
ALTER TABLE credit_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY backend_access ON credit_movements TO flamingo_app USING (true) WITH CHECK (true);
UPDATE settings SET value='3' WHERE key='schema_version';
RESET search_path;
COMMIT;
